TARGET  := read_mt.exe
INCS = -I ../lib/network -I ../lib/utils -I ../lib/base -I ../lib -I ../lib/httptools
LIBS = -L ../lib/utils -lutils -L ../lib/network -lnetwork -L ../lib/base -lbbtbase  -L ../lib/httptools -lhttptools -L ../lib/base -lbbtbase -lrestclient-cpp -lcurl -L ../../../protobuf-3.5.0/lib -L ../../lib -lprotobuf -L /usr/local/lib/ -lleveldb -lrdkafka -lfc -lssl -lcrypto  -levent  -Wl,-Bstatic -lfc -lsecp256k1 -lev -ljansson -lmpdec -lmysqlclient -lz -lhiredis -lboost_system -lboost_thread -lboost_chrono -lboost_filesystem -lboost_date_time -lboost_context -lboost_coroutine -lboost_iostreams -Wl,-Bdynamic -lm -lpthread -ldl
include ../makefile.inc
